### ISSUE TITLE
Great Work and I wish do video on what u have now!

### ISSUE THREAD

**Issue by chrisgate** [ANMSalman/PermissionAuthDemo#1]
I enjoyed going thru your code and how u handle permission and Results was a revelation to me.
I just wish u can consider doing video on it so we can learn more.

Cheers

**Comment by ANMSalman** [comment]
Hi @chrisgate.

Thank you for your feedback. I'm working on a detailed video tutorial and a blog as well. Until then you could refer to one of the following blogs to learn more.

https://codewithmukesh.com/blog/permission-based-authorization-in-aspnet-core/
https://www.zehntec.com/blog/permission-based-authorization-in-asp-net-core/

Cheers

**Comment by chrisgate** [comment]
thank you........you are a good person.

Cheers
